# Generated by Django 4.0.1 on 2022-03-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0004_ban'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['book_title']},
        ),
    ]
