# Generated by Django 3.2.13 on 2022-05-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0004_auto_20220507_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='date_start',
            field=models.DateField(auto_now_add=True),
        ),
    ]
