# Generated by Django 3.2.13 on 2022-05-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0005_alter_fine_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='pay_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
