# Generated by Django 4.0.1 on 2022-04-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0002_author_slug_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='fine',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='fine_date',
            field=models.DateField(null=True),
        ),
    ]
