# Generated by Django 3.2.13 on 2022-05-07 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lib_app', '0003_reading_fine_reading_fine_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='fine',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='fine_date',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='reading_days',
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('pay_status', models.BooleanField()),
                ('pay_date', models.DateField(null=True)),
                ('reading_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_app.reading')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
