# Generated by Django 3.2.13 on 2022-05-10 19:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lib_app', '0006_alter_fine_pay_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fine',
            unique_together={('user_id', 'reading_id')},
        ),
    ]
