# Generated by Django 3.2.13 on 2022-05-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0010_auto_20220522_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_book',
            field=models.CharField(max_length=50, unique=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_book',
            field=models.CharField(max_length=50, unique=True, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
