# Generated by Django 3.2.13 on 2022-06-01 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0011_auto_20220522_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Ban',
        ),
        migrations.DeleteModel(
            name='Reserve',
        ),
    ]
